# Generated by Django 5.2.17 on 2026-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rental_type',
            field=models.CharField(choices=[('rental', 'Rent a Car'), ('self_drive', 'Self Drive')], default='rental', max_length=20),
        ),
    ]
