databases:
  - name: thakur-logistics-db
    plan: free

services:
  # DJANGO BACKEND
  - type: web
    name: thakur-logistics-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thakur-logistics-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: WEB_CONCURRENCY
        value: 4

  # STATIC FRONTEND
  - type: web
    name: thakur-logistics-frontend
    runtime: static
    buildCommand: "./build-frontend.sh"
    staticPublishPath: "./dist"