# Generated by Django 5.2.17 on 2026-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='happy_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='professional_drivers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vehicles_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
